### ISSUE TITLE
MINOR issue. additional space in header for VIGNET: '(30, 30)' should be '(30,30)'

### ISSUE THREAD

**Issue by vpicouet** [astromatic/sextractor#22]
TOPCAT can not read vignet properly in sextractor outputs.
After asking TOPCAT lead developper it seems that this was a small issue in the way the header is written either by sextractor or LDACTOOLS:
```
Topcat's reader was failing to parse this array shape declaration because
of the space following the comma.  Looking at the FITS standard 
(FITS 4.0 sec 7.3.2) it does not say that spaces are permitted here, 
so I'd say that this header is actually in error (it should be '(30,30)'),
so that may be a minor Sextractor bug.  However it's clear what the
intention is, and evidently this usage exists, so I've fixed topcat 
to cope with this.
```

Python already incorporated this hack and TOPCAT will in the next versions so it might not be needed to solve it, just wanted to let you know,

Best

Vincent

**Comment by mbtaylor** [comment]
Looking closer it may not be SExtractor at fault here, so apologies if I got the blame wrong in my comment quoted above by @vpicouet !  The file in question has a Primary HDU with `ORIGIN  = 'SExtractor'` but the offending TDIMn header is in an extension HDU marked `XTENSION= 'BINTABLE'           / THIS IS A BINARY TABLE (FROM THE LDACTOOLS)`.

**Comment by ebertin** [comment]
SExtractor was indeed the culprit. I was not aware of this rule. Thanks!
