### ISSUE TITLE
SExtractor-Photutils-aperturephotometry-  aperture_photometry FLUX_APER differences

### ISSUE THREAD

**Issue by xiaoguaishoubaobao** [astromatic/sextractor#29]
Below is my full question
please help me

https://github.com/astropy/photutils/issues/1411

**Comment by xiaoguaishoubaobao** [comment]
Is this a bug of Sextractor?

**Comment by xiaoguaishoubaobao** [comment]
The problem is solved. Sex uses the diameter, and the other two software uses the radius. It is the same when they are unified.

**Comment by ebertin** [comment]
HI @xiaoguaishoubaobao, thanks for finding out!
