### ISSUE TITLE
Problem with sh autogen.sh and ./configure

### ISSUE THREAD

**Issue by tahereparto** [astromatic/sextractor#36]
Hello.
I try to install Sextractor on my fedora. With the **sh autogen.sh** command, I get the following error, and I can not proceed with the installation. The ./configure does not work.

**The error:**
ERROR:  Unable to locate GNU Autoconf.

ERROR:  To prepare the SCAMP build system from scratch,
        at least version 2.52 of GNU Autoconf must be installed.

autogen.sh does not need to be run on the same machine that will
run configure or make.  Either the GNU Autotools will need to be installed
or upgraded on this system, or autogen.sh must be run on the source
code on another system and then transferred to here. -- Cheers!

**Comment by ebertin** [comment]
Hi @tahereparto,
To build the tool from the source you will need to install some development packages (I hope that the list is sufficiently complete, it does not include the c compiler and the make command) using the package manager dnf:
`sudo dnf install autoconf automake libtool pkgconfig fftw-devel atlas-devel libcurl-devel plplot-devel`

**Comment by tahereparto** [comment]
Thank you so much. Very helpful.

**Comment by tahereparto** [comment]
I just want to add, one need to install (at least in my case) `apt-get install libfftw3-dev` or on Fedora 'dnf install fftw-devel', then sh autogen.sh and ./configure works.
